### ISSUE TITLE
Vias on wrong layers

### ISSUE THREAD

**Issue by qaqcvc** [realthunder/fcad_pcb#68]
First of all, I would like to thank all the contributors for this wonderful tool. It is a lifesaver!

In this practive, I am tring to output the pcb with micro layers from 1-2 and 23-24, as well as burried vias from 2-23. But the output shows wrong vias locations:
![image](https://github.com/realthunder/fcad_pcb/assets/52302145/11a2c1a5-f0bf-4d47-bc35-d347c69ee924)

Is it a bug, or do I possibly set smethong wrong?
I have checked the setting of vias in Kicad, they are all rightly set with right 3d view in Kicad.
![image](https://github.com/realthunder/fcad_pcb/assets/52302145/6363b017-6550-4620-bac4-79e51417a834)

With a deeper observation, it seems that in Freecad, all vias more moved 2 layers below. But the holes are rightly located.
![image](https://github.com/realthunder/fcad_pcb/assets/52302145/dd97b38d-419a-43cf-b6aa-d636c68d2cf7)

**Comment by qaqcvc** [comment]
I am using kicad 6 and 7 (test both), and Freecad 0.19

**Comment by realthunder** [comment]
Is it possible to post a sample file showing the problem?

**Comment by qaqcvc** [comment]
Hi realthunder, thank you for checking! Please find one minimum test file here: [test.zip](https://github.com/realthunder/fcad_pcb/files/11899503/test.zip)

There are several issues in this practice:
1. I need to at least add one through via, otherwise it gives me error:  line 991, in _makeArea
    if not force and obj[0].TypeId == 'Path::FeatureArea' and (
<class 'IndexError'>: list index out of range
2. Normally when I select add via annular ring only for connected layers, all rings will be generated.
3. 1-2 micro vias and middle vias are on wrong positions
![image](https://github.com/realthunder/fcad_pcb/assets/52302145/a7227965-047d-4fa1-81ab-98848e47b79f)
4. Wrong holes on top and bottom layers
![image](https://github.com/realthunder/fcad_pcb/assets/52302145/e40bf339-93b4-4b63-8c70-7539f13b09c9)
![image](https://github.com/realthunder/fcad_pcb/assets/52302145/3a8a2c3c-53f0-458b-9c21-f30cf7245bde)
5. Although successfully generate the 3d model but got error, this error occasionally occurs.
line 11, in <module>     Part.show(coppers)   <class 'TypeError'>: argument 1 must be Part.Shape, not Part.Feature

Thank you very much realthunder! As a hardware engineer, I tried to use chatgpt to find out possible solutions, but no good. If this issue can be solved, it would be really helpful for folks working on complex multiple layers design!

**Comment by realthunder** [comment]
Just added some fixes. Please sync the repo and test. You can close the issue if everything is fine.

**Comment by qaqcvc** [comment]
Hi realthunder, thanks for your reponse! From my side, the issue seems to consist:
![image](https://github.com/realthunder/fcad_pcb/assets/52302145/3a1f5c5b-19b5-4761-96b7-bb24bfa0b96a)
![image](https://github.com/realthunder/fcad_pcb/assets/52302145/1e025dbf-bdad-491a-932c-8b63a23bd16f)

Thank you for your precious time.

**Comment by realthunder** [comment]
Have you synced the repo, `git pull` maybe? Is the following model correct?

![image](https://github.com/realthunder/fcad_pcb/assets/1207888/3c6f8628-a35d-4860-840c-7e73c10d9c91)

![image](https://github.com/realthunder/fcad_pcb/assets/1207888/878a8dd5-f52d-47bc-a453-6ace7f96e174)

![image](https://github.com/realthunder/fcad_pcb/assets/1207888/bf5edb08-224d-4611-bd7a-4f99548c1876)

**Comment by qaqcvc** [comment]
Hi realthunder, Sorry I am not familiar with git, do not know why issue occurs when directly download the complete codes. When I only download kicad.py, it works! Now I do not need to seprately generate top,middle and bot layers.

But if the layout does not contain any through via, the fuse cannot be made. This issue can be escaped by mannually adding a dommy through via though.
![image](https://github.com/realthunder/fcad_pcb/assets/52302145/2b768d1d-afd9-4554-b902-747d5b74ea34)

And I constantly got this error:
![image](https://github.com/realthunder/fcad_pcb/assets/52302145/fbae4b9a-86c4-49af-af72-0d5b564b1677)

It would be great if 'connected layers only' is implemented, which can largely reduce mesh complexity by removing unnecessary rings.
![image](https://github.com/realthunder/fcad_pcb/assets/52302145/a0f5872b-9abc-466f-be70-6ab3e7137258)
![image](https://github.com/realthunder/fcad_pcb/assets/52302145/eef01a59-9898-4c1a-ab57-39cea25ab376)

Thank you for your time!

**Comment by realthunder** [comment]
> But if the layout does not contain any through via, the fuse cannot be made. This issue can be escaped by mannually adding a dommy through via though.

Please always provide a sample file showing the problem.

> And I constantly got this error:

The macro code you are using is not mine. Is it hosted in some git repo so that I can take a look?

> It would be great if 'connected layers only' is implemented, which can largely reduce mesh complexity by removing unnecessary rings.

Does that means the via is supposed to only have annular ring in the start and end layers?

**Comment by qaqcvc** [comment]
> Please always provide a sample file showing the problem.
In you new added "blind_buried_vias.kicad_pcb" file, if you remove the only though hole via, the fuse will not be made.
![image](https://github.com/realthunder/fcad_pcb/assets/52302145/5e5699b7-07c7-4233-9c4e-83621e261544)

> The macro code you are using is not mine. Is it hosted in some git repo so that I can take a look?
I am using these codes:
```
from fcad_pcb import kicad
pcb = kicad.KicadFcad(r'C:\Users\25423\AppData\Roaming\FreeCAD\Macro\fcad_pcb\tests\blind_buried_vias.kicad_pcb')
pcb.add_feature = True

coppers = pcb.makeCoppers(shape_type='solid',holes=True,fuse=True)
Part.show(coppers)
```

> Does that means the via is supposed to only have annular ring in the start and end layers?
For example, if vias are connected with layer 1,3,5... There should be no annular rings at layer 2,4.., because the fuse doesnot need to connect with these layers. The added annular rings only add unnecessary mesh elements. In my PCB design, there are more than 200 vias. The additional elements could bring addtional several hours of simulation.

**Comment by realthunder** [comment]
> In you new added "blind_buried_vias.kicad_pcb" file, if you remove the only though hole via, the fuse will not be made.

This problem has been fixed. Please download kicad.py and try again.


> And I constantly got this error:
> ![image](https://github.com/realthunder/fcad_pcb/assets/52302145/fbae4b9a-86c4-49af-af72-0d5b564b1677)

`Part.show()` is for `Shape` not `Feature`. It is only necessary if `pcb.add_feature = False`, otherwise, there is no need to call that.



> For example, if vias are connected with layer 1,3,5... There should be no annular rings at layer 2,4.., because the fuse doesnot need to connect with these layers.

Can you please make a sample file with this? It seems that KiCad has an option to remove unused vias/pads. Make sure to enable this option.

**Comment by qaqcvc** [comment]
Hi realthunder, thnak you! The first two issues are solved.
Regarding the last issue, please ref this file: 
[blind_buried_vias.zip](https://github.com/realthunder/fcad_pcb/files/11931080/blind_buried_vias.zip)
In this layout, there are two though vias, one has annular rings at all layers; while another one has annular rings only with connected layers. 
![image](https://github.com/realthunder/fcad_pcb/assets/52302145/e662463f-a6ab-41ae-98e2-af514e2c8110)
![image](https://github.com/realthunder/fcad_pcb/assets/52302145/2f95bbfe-b033-4e29-af60-06cade2787c8)

**Comment by realthunder** [comment]
I have updated the code. Please try. If you want to be thorough, please make a board with actually connected and unconnected tracks and zones. Maybe you can also try this options on pads (with various orientations), which I haven't implemented yet. I can add that if you can make sample board with those.

**Comment by qaqcvc** [comment]
Hi realthunder, sorry for the late reply. I have tested your new kicad.py file, this issue is not solved, I think we have different understanding of the concept of "connected layers". Please have a look on the figure below. 
With connected first layer (connected with trace), the annular ring exists, while for the layers 2,3... , because at these layers this via is not connected to any trace or copper pool, the annular rings need to be removed.
![image](https://github.com/realthunder/fcad_pcb/assets/52302145/b85e75e1-ec51-41d9-9acc-bf5e3c206576)

Here is a sample kicad layout file for you to have a test.
[blind_buried_vias.zip](https://github.com/realthunder/fcad_pcb/files/12005944/blind_buried_vias.zip)

Thank you for your consistent contribution!

**Comment by qaqcvc** [comment]
Another question would be,  how can I define the via thickness? Last time I measured in Freecad, seems the thickness of the vias fuse is 35um. Is it possible to modify the thickness by ourselves? Thank you.

**Comment by realthunder** [comment]
Please make sure you have updated the kicad.py file. This is what I get when running your files on my compouter.

![image](https://github.com/realthunder/fcad_pcb/assets/1207888/70df60ee-3067-4339-b0bb-71bb0e070d5d)



> Another question would be, how can I define the via thickness? Last time I measured in Freecad, seems the thickness of the vias fuse is 35um. Is it possible to modify the thickness by ourselves? Thank you.

Do you mean the thickness of the middle cylinder? If it is the annular ring, then the thickness is determined by the layer thickness.

**Comment by qaqcvc** [comment]
Hi realthunder, it seems last time I did not update kicad.py successfully.
But with the new kicad.py, I still got one bug with the blid_buried_vias.kicad_pcb file.

I can successfully generate this figure with the original kicad_pcb.
![image](https://github.com/realthunder/fcad_pcb/assets/52302145/698ef930-b2d7-4f61-a62d-23ad3f70a289)

However, if I press 'B' to fill all zones, then try to generate from Freecad, I will meet this error:
```
11:53:47  making all copper layers...
11:53:47      making holes...
11:53:47        pad holes: 0, skipped: 0
11:53:47        oval holes: 0
11:53:47        total holes added: 8
11:53:47      holes done
11:53:47    making copper layer F.Cu...
11:53:47      making pads...
11:53:47        checking edge cuts
11:53:47          making 10 lines
11:53:47        making 10 lines
11:53:47        checking edge cuts
11:53:47          making 10 lines
11:53:47        making 10 lines
11:53:47  Traceback (most recent call last):
  File "C:/Users/25423/AppData/Roaming/FreeCAD/Macro/readLayout@001.FCMacro", line 10, in <module>
    coppers = pcb.makeCoppers(shape_type='solid',holes=True,fuse=True)
  File "C:/Users/25423/AppData/Roaming/FreeCAD/Macro\fcad_pcb\kicad.py", line 2221, in makeCoppers
    copper = self.makeCopper(shape_type,t,fit_arcs=fit_arcs,
  File "C:/Users/25423/AppData/Roaming/FreeCAD/Macro\fcad_pcb\kicad.py", line 2134, in makeCopper
    obj = getattr(self,'make{}'.format(name))(fit_arcs=sub_fit_arcs,
  File "C:/Users/25423/AppData/Roaming/FreeCAD/Macro\fcad_pcb\kicad.py", line 1815, in makePads
    if filter_unconnected(v, (v.at[0], v.at[1])):
  File "C:/Users/25423/AppData/Roaming/FreeCAD/Macro\fcad_pcb\kicad.py", line 1723, in filter_unconnected
    excludes = [self.findLayers(s)[0] for s in getattr(v, 'zone_layer_connections', [])]
  File "C:/Users/25423/AppData/Roaming/FreeCAD/Macro\fcad_pcb\kicad.py", line 1723, in <listcomp>
    excludes = [self.findLayers(s)[0] for s in getattr(v, 'zone_layer_connections', [])]
<class 'AttributeError'>: 'KicadFcad' object has no attribute 'findLayers'
```
You can try to test in your PC with this file, where I just refilled all zones.
[blind_buried_vias.zip](https://github.com/realthunder/fcad_pcb/files/12061225/blind_buried_vias.zip)
If I delete the via with the setting "annular rings connected layers only", layout can be generated successfully.

> Do you mean the thickness of the middle cylinder? If it is the annular ring, then the thickness is determined by the layer thickness.

![image](https://github.com/realthunder/fcad_pcb/assets/52302145/44f9e7b3-b182-42d2-aedf-941ce2314470)
Normally the thickness of the covered copper inside vias holes is around 25um. But it would be great if we can have some control of this parameters. For example, one of the common practices is to make the micro vias between 1-2 layers (and 23-24 layers) are filled completelly with copper inside the holes, but for inside blind vias, the covered copper is around 25um.

In your Kicad.py setting, seems it is set defaultlly to 35um?
![image](https://github.com/realthunder/fcad_pcb/assets/52302145/d82101f9-3b91-47eb-a0b0-2826271a82a1)
It would be perfect to have some flexibiliy on settings of 0.165mm.

Thank you for your precious time!

**Comment by qaqcvc** [comment]
Hi realthunder, I have figured out how to set the thickness of the vias. That is by setting the value of hole_size_offset
```
pcb = kicad.KicadFcad(r'file name',hole_size_offset=0.055)
```
By default, the thickness of the vias is 52.5um. And every 0.001 of hole_size_offset represents to reduce the thickness by 0.5um. So 0.055 means 52.5um - 55*0.5um = 25um. I did not go into details to check how this 52.5um is calculated, I just know that several months ago, the default thickness seems to be 35um. Could you briefly explain the method to calculate the thickness?

This error still exists in other test practices.
> However, if I press 'B' to fill all zones, then try to generate from Freecad, I will meet this error:
```
11:53:47  making all copper layers...
11:53:47      making holes...
11:53:47        pad holes: 0, skipped: 0
11:53:47        oval holes: 0
11:53:47        total holes added: 8
11:53:47      holes done
11:53:47    making copper layer F.Cu...
11:53:47      making pads...
11:53:47        checking edge cuts
11:53:47          making 10 lines
11:53:47        making 10 lines
11:53:47        checking edge cuts
11:53:47          making 10 lines
11:53:47        making 10 lines
11:53:47  Traceback (most recent call last):
  File "C:/Users/25423/AppData/Roaming/FreeCAD/Macro/readLayout@001.FCMacro", line 10, in <module>
    coppers = pcb.makeCoppers(shape_type='solid',holes=True,fuse=True)
  File "C:/Users/25423/AppData/Roaming/FreeCAD/Macro\fcad_pcb\kicad.py", line 2221, in makeCoppers
    copper = self.makeCopper(shape_type,t,fit_arcs=fit_arcs,
  File "C:/Users/25423/AppData/Roaming/FreeCAD/Macro\fcad_pcb\kicad.py", line 2134, in makeCopper
    obj = getattr(self,'make{}'.format(name))(fit_arcs=sub_fit_arcs,
  File "C:/Users/25423/AppData/Roaming/FreeCAD/Macro\fcad_pcb\kicad.py", line 1815, in makePads
    if filter_unconnected(v, (v.at[0], v.at[1])):
  File "C:/Users/25423/AppData/Roaming/FreeCAD/Macro\fcad_pcb\kicad.py", line 1723, in filter_unconnected
    excludes = [self.findLayers(s)[0] for s in getattr(v, 'zone_layer_connections', [])]
  File "C:/Users/25423/AppData/Roaming/FreeCAD/Macro\fcad_pcb\kicad.py", line 1723, in <listcomp>
    excludes = [self.findLayers(s)[0] for s in getattr(v, 'zone_layer_connections', [])]
<class 'AttributeError'>: 'KicadFcad' object has no attribute 'findLayers'

```

Thank you for your time realthunder.

**Comment by realthunder** [comment]
The `findLayers()` is a typo, should be `findLayer()`. It's fixed now.

About the `hole_size_offset`, it specifies the amount of decrease to plated hole diameter. For non-plated holes, this is the amount of increase in diameter. The offset is added to workaround CAD kernel tolerance issue.

**Comment by realthunder** [comment]
Could you please post the files that caused those errors?

The base wall thickness of a plated hole is determined by the copper layer thickness setting. Are you using different copper layer thickness? Please provide a file showing variance in hole wall thickness.

**Comment by qaqcvc** [comment]
Hi realthunder, you can check with 'blind_buried_vias.kicad_pcb' in your fcad_pcb test folder with the newest kicad.py file.
It will generate this error:
```
  File "D:/Users/t84201115/AppData/Roaming/FreeCAD/Macro/Read_PCBLayout.FCMacro", line 14, in <module>
    coppers = pcb.makeCoppers(shape_type='solid',  fuse=True, holes=True)
  File "D:/Users/t84201115/AppData/Roaming/FreeCAD/Macro\fcad_pcb\kicad.py", line 2221, in makeCoppers
    copper = self.makeCopper(shape_type,t,fit_arcs=fit_arcs,
  File "D:/Users/t84201115/AppData/Roaming/FreeCAD/Macro\fcad_pcb\kicad.py", line 2134, in makeCopper
    obj = getattr(self,'make{}'.format(name))(fit_arcs=sub_fit_arcs,
  File "D:/Users/t84201115/AppData/Roaming/FreeCAD/Macro\fcad_pcb\kicad.py", line 1815, in makePads
    if filter_unconnected(v, (v.at[0], v.at[1])):
  File "D:/Users/t84201115/AppData/Roaming/FreeCAD/Macro\fcad_pcb\kicad.py", line 1723, in filter_unconnected
    excludes = [self.findLayer(s)[0] for s in getattr(v, 'zone_layer_connections', [])]
  File "D:/Users/t84201115/AppData/Roaming/FreeCAD/Macro\fcad_pcb\kicad.py", line 1723, in <listcomp>
    excludes = [self.findLayer(s)[0] for s in getattr(v, 'zone_layer_connections', [])]
  File "D:/Users/t84201115/AppData/Roaming/FreeCAD/Macro\fcad_pcb\kicad.py", line 662, in findLayer
    raise KeyError('layer {} not found'.format(layer))
<class 'KeyError'>: 'layer " not found'
```

Right now, I am rolling back to 20220721 kicad.py version.

BTW, if you have time and interest, I found another issue with fcad_pcb to export model to step.
https://github.com/FreeCAD/FreeCAD/issues/10053

Thank you as always.

**Comment by HJFSTX** [comment]
Hi realthunder,

I'm using the latest version of the script with mixed success on the via issues being resolved.

I am now getting an error that I've narrowed down to the via holes being made:

```
15:09:12  Traceback (most recent call last):
  File "C:/Users/HJFSTX/AppData/Roaming/FreeCAD/Macro/Import_PCB_Full.FCMacro", line 12, in <module>
    pcb.makeCoppers(shape_type = 'solid', holes = True, fuse = True, fit_arcs = True)
  File "C:\Users\HJFSTX\AppData\Roaming\FreeCAD\Macro\fcad_pcb\kicad.py", line 2248, in makeCoppers
    drills = self.makeHoles(shape_type='solid',prefix=None,
  File "C:\Users\HJFSTX\AppData\Roaming\FreeCAD\Macro\fcad_pcb\kicad.py", line 1534, in makeHoles
    w = make_circle(Vector(s))
  File "C:\Users\HJFSTX\AppData\Roaming\FreeCAD\Macro\fcad_pcb\kicad.py", line 197, in make_circle
    return Part.Wire(Part.makeCircle(size.x*0.5))
<class 'Part.OCCError'>: creation of circle failed
```
If I remove the vias, the error goes away. I do have some oval PTH pads that will generate fine.

Many thanks and best regards.

**Comment by qaqcvc** [comment]
> Hi realthunder,
> 
> I'm using the latest version of the script with mixed success on the via issues being resolved.
> 
> I am now getting an error that I've narrowed down to the via holes being made:
> 
> ```
> 15:09:12  Traceback (most recent call last):
>   File "C:/Users/HJFSTX/AppData/Roaming/FreeCAD/Macro/Import_PCB_Full.FCMacro", line 12, in <module>
>     pcb.makeCoppers(shape_type = 'solid', holes = True, fuse = True, fit_arcs = True)
>   File "C:\Users\HJFSTX\AppData\Roaming\FreeCAD\Macro\fcad_pcb\kicad.py", line 2248, in makeCoppers
>     drills = self.makeHoles(shape_type='solid',prefix=None,
>   File "C:\Users\HJFSTX\AppData\Roaming\FreeCAD\Macro\fcad_pcb\kicad.py", line 1534, in makeHoles
>     w = make_circle(Vector(s))
>   File "C:\Users\HJFSTX\AppData\Roaming\FreeCAD\Macro\fcad_pcb\kicad.py", line 197, in make_circle
>     return Part.Wire(Part.makeCircle(size.x*0.5))
> <class 'Part.OCCError'>: creation of circle failed
> ```
> 
> If I remove the vias, the error goes away. I do have some oval PTH pads that will generate fine.
> 
> Many thanks and best regards.


Hi HJFSTX, I also met this problem before. I then realized that the size of the via is too small in my case. The smallest size allowable in my board is 0.31,0.13 in my board. And this minimum size is limited by the thickness of the copper layer if I understand rightly, as the thickness of the via tube is proportional to the copper thickness.

You may try to change the size of the via to see if this issue persists.

**Comment by HJFSTX** [comment]
@realthunder and @luzpaz 

I have been extensively using this script and am noticing what I am calling "phantom geometry" that is causing huge unforeseen issues in FEA. The geometry in question seems to have areas that are either shorted or totally unconnected, although they visually appear to be just fine. I think our issues are related.

**Comment by realthunder** [comment]
Is it possible to provide a test file showing the problem?

**Comment by HJFSTX** [comment]
@realthunder

I cannot post the exact source files, but if I encounter issues again I will attempt to replicate. Some of the issues I encountered were due to user error, so it may have been a false alarm.

**Comment by HJFSTX** [comment]
@realthunder 

I'm again having some issues creating holes/vias. Please see below for the error:

`08:59:10  Traceback (most recent call last):
  File "C:/Users/HJFSTX/AppData/Roaming/FreeCAD/Macro/Import_PCB_Full_No_Holes_No_Zone_Inflate.FCMacro", line 12, in <module>
    pcb.makeCoppers(shape_type = 'solid', holes = False, fuse = True, fit_arcs = True)
  File "C:\Users\HJFSTX\AppData\Roaming\FreeCAD\Macro\fcad_pcb\kicad.py", line 2239, in makeCoppers
    hole_coppers = self.makeHoles(shape_type='solid',prefix=None,
  File "C:\Users\HJFSTX\AppData\Roaming\FreeCAD\Macro\fcad_pcb\kicad.py", line 1484, in makeHoles
    size = Vector(p.drill[0],p.drill[1])
  File "C:\Users\HJFSTX\AppData\Roaming\FreeCAD\Macro\fcad_pcb\kicad_parser\sexp_parser\sexp_parser.py", line 146, in __getitem__
    v = self._value[key]
<class 'KeyError'>: (1,)`

Any idea what's going on here?

**Comment by qaqcvc** [comment]
Hi realthunder, thank you for your contribution on facd_pcb. I think your script to output real 3d layout is till now the only solution. I do not see any intention from Kicad to support this feature in the future. 

Just curious, would you consider to make a simple workbench for fcad_pcb, which has better UI and tuning options? The installation would be also easier. That would be tons of help for our FEM guys. 

BTW, I have shifted my freecad to your linkstage. Really like the features you developed. Thank you!

**Comment by realthunder** [comment]
> I'm again having some issues creating holes/vias. Please see below for the error:

You seem to be using an older version of this repo. Could you please update it and try again?

**Comment by realthunder** [comment]
> Just curious, would you consider to make a simple workbench for fcad_pcb, which has better UI and tuning options?

I may extend it into a FreeCAD macro with UI for settings. Not in the near future, though. Quite busy these days.

**Comment by realthunder** [comment]
> Just curious, would you consider to make a simple workbench for fcad_pcb, which has better UI and tuning options?

Or, you can try the [kicadStepUp](https://github.com/easyw/kicadStepUpMod) workbench.

**Comment by HJFSTX** [comment]
> > I'm again having some issues creating holes/vias. Please see below for the error:
> 
> You seem to be using an older version of this repo. Could you please update it and try again?

I pulled the latest version, tried again, and got the same result.

**Comment by realthunder** [comment]
Could you please send me the file having problem?
